DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;


CREATE TABLE ROLES (
    RID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME IN ('ADMIN', 'TEACHER' , 'CLIENT'))
);

CREATE TABLE USERS (
	UID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(60) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
    ROLE_ID INT NOT NULL DEFAULT 3,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(RID)
);

CREATE TABLE EVENTS (
    EID SERIAL PRIMARY KEY,
	CLASS_TYPE VARCHAR(60) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    TEA_ID INT NOT NULL,
    CLIENT_ID INT NOT NULL,
    FOREIGN KEY (TEA_ID) REFERENCES USERS(UID),
    FOREIGN KEY (CLIENT_ID) REFERENCES USERS(UID)
);

INSERT INTO ROLES (NAME) VALUES 
    ('ADMIN'),
	('TEACHER'),
    ('CLIENT');



select * from ROLES;